import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from 'next/font/google';
import NavBar from "./Component/NavBar";
import Footer from "./Component/Footer";
import NavBar2 from "./Component/NavBar2";
const inter = Inter({ subsets: ['latin'] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Book Fair",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${inter.className}`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar2></NavBar2>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
